icon-theme = "Papirus-Dark"
terminal="alacritty -e {cmd}"

# oxcarbon
[colors]
background=161616dd
text=ffffffff
match=ee5396ff
selection-match=ee5396ff
selection=262626ff
selection-text=33b1ffff
border=525252ff

# Catppuccin
#[colors]
#background=303446dd
#text=c6d0f5ff
#prompt=b5bfe2ff
#placeholder=838ba7ff
#input=c6d0f5ff
#match=8caaeeff
#selection=626880ff
#selection-text=c6d0f5ff
#selection-match=8caaeeff
#counter=838ba7ff
#border=8caaeeff
