# Config/data paths
GIT_CONFIG_GLOBAL=$HOME/.config/gitconfig
LESSHISTFILE=-
GNUPGHOME=$HOME/.local/share/gnupg
CARGO_HOME=$HOME/.local/share/cargo
RUSTUP_HOME=$HOME/.local/share/rustup
PYTHON_HISTORY=/dev/null
GOPATH=$HOME/.local/share/go
BUN_INSTALL=$HOME/.local/share/bun
ANDROID_SDK_HOME=$HOME/.local/share/android-sdk
ANDROID_HOME=$ANDROID_SDK_HOME

# Path extensions
PATH=$HOME/.local/bin:$PATH
PATH=$BUN_INSTALL/bin:$PATH
PATH=$CARGO_HOME/bin:$PATH
